### ISSUE TITLE
🌱  Kale week  3 - Set up axe-core tests for storage and sharing

### ISSUE THREAD

**Issue by trallard** [Quansight-Labs/jupyter-a11y-mgmt#105]
## Tasks to complete

- [x] #107
- [x] #106

**Comment by gabalafou** [comment]
I checked the first item above because I think it was completed in https://github.com/Quansight-Labs/jupyter-a11y-mgmt/issues/107.

Since both tasks are checked this can be closed I think. However, I'm not sure I understand why #106 was closed, as opposed to moved to another work cycle because where's the work? where's the pr?

**Comment by trallard** [comment]
added more details in #106
