### ISSUE TITLE
Define 1-2 tests for Playwright and Galata

### ISSUE THREAD

**Issue by trallard** [Quansight-Labs/jupyter-a11y-mgmt#107]
From #95  select two candidates for automated testing

**Comment by isabela-pf** [comment]
Pulling over my comment from #95
> I think any of these scenarios can be tested first based on what's easiest for development to start with. If it's helpful for me to choose, I think `2.1.2 No keyboard trap` is the easiest to start with because 
> - it can actually pass in JupyterLab now (compared to focus order, which will 100% fail right now)
> - it can run well with a full "page" of JupyterLab and doesn't need a subset of the UI
> - it's not blocked by any other tests

After that, I think `2.4.3 Focus Order` would be my next choice because
- it is a critical experience for users
- it can run well with a full "page" of JupyterLab and doesn't need a subset of the UI
- it has some of the clearest success criteria
but it will fail right now. We don't actually have focus order fixed right now.

If we don't want a test we know is going to fail right away, then I'd go with `2.5.6 Concurrent input mechanisms` because
- it can run well with a full "page" of JupyterLab and doesn't need a subset of the UI
- I think there's precedent for automating different simulated input methods, so you may not be working totally from scratch.

**Comment by trallard** [comment]
1. Scoped and implemented is the `no tab trap`

**Comment by trallard** [comment]
@gabalafou and @isabela - these decisions that have been made re the tests that are being implemented and are in progress should be updated in the roadmap

**Comment by isabela-pf** [comment]
Do you mean you want a PR to [this grant roadmap](https://jupyter-a11y.netlify.app/roadmap/intro.html)?

I was going to close this issue since I thought the decision had been made for this term, but I will wait to hear what the final step is.

**Comment by trallard** [comment]
Let's close this and we can update the roadmap in the upcoming mini sprint
