### ISSUE TITLE
🌱 Kale week 6 - Final test implementation

### ISSUE THREAD

**Issue by trallard** [Quansight-Labs/jupyter-a11y-mgmt#115]
## Tasks to complete

- [ ] #116
- [x] #117

**Comment by gabalafou** [comment]
If we move #118 out of this cycle and if I can get one more Playwright test in, then I think all of the subtasks for this issue will be done

**Comment by gabalafou** [comment]
There's still a fair amount to do for this to be where I would like it to be. Specifically, I want to:

- Clean up the test names so that the report that Playwright generates is more self-explanatory. For example, I want to rename the file `a11y.test.ts` to something else because what does that file name even mean? Should be something more like `testable-wcag-violations.test.ts` or something like that
- Add another Playwright test
- Hook up Tony's build+test code to Github workflows, so that:
    - We can run the tests against JupyterLab on a cron job (weekly or nightly or whatever makes sense)
    - Anybody can run the tests against a specific commit (note: older commits will not be supported)
