### ISSUE TITLE
Finish implementation of automated scripts - 🌱 Kale

### ISSUE THREAD

**Issue by trallard** [Quansight-Labs/jupyter-a11y-mgmt#116]
@gabalafou  to complete the implementation of Isabela's scripts

**Comment by gabalafou** [comment]
I've created a pull request for a [variation of the test](https://github.com/Quansight-Labs/accessibility/pull/2) that Isabela titled [No keyboard trap](https://github.com/Quansight-Labs/jupyter-a11y-mgmt/issues/95#issuecomment-1118978913). Instead of testing the particular tabbing order that she suggested, I wanted to write a more generic test for the ability to tab-cycle through a page. 

The PR is ready for review. The only reason it is in draft mode only because I had to branch off of [the axe-gitpod PR's](https://github.com/jupyter/accessibility/pull/83) branch.

**Comment by gabalafou** [comment]
Another thought. I want to think of way to pair the human-readable scripts with the test code. Perhaps this is as simple as creating a .md file that lives side by side with the test js file? For example, with reference to my open PR: 

```
tests/
tab-loop-no-trap.test.js
tab-loop-no-trap.md
```

**Comment by trallard** [comment]
> Another thought. I want to think of way to pair the human-readable scripts with the test code. 

This will be tackled by #113  we need to make sure that the tests and scripts x-reference each other

**Comment by gabalafou** [comment]
I want to try to get one more Playwright test in from the one's that Isabela wrote
