### ISSUE TITLE
Identify shared components between Retrolab and Jlab

### ISSUE THREAD

**Issue by trallard** [Quansight-Labs/jupyter-a11y-mgmt#68]
## Summary

@gabalafou  will be working on discovering the shared components between JLab and Retrolab to drive #4 

## Acceptance Criteria

- Identify the components that we need to test/improve (prioritise)
- Share the findings with @trallard  to start working on #4

**Comment by gabalafou** [comment]
After taking a long time [deep-diving into JupyterLab](https://github.com/gabalafou/map-jupyterlab-frontend-components) so that I could truly understand how it loads itself into the browser, I was able to do a comparatively [quick comparison between RetroLab and JupyterLab](https://hackmd.io/@gabalafou/Syevi8mTF).

Based on the above work, these are the conclusions I have come to so far. Perhaps wediscuss them in our next team meeting? 

- tl;dr-- from my perspective, there’s very little new code in RetroLab to target for our accessibility work. It looks like RetroLab mostly re-arranges and omits UI elements from JupyterLab.
- So my take is: we should focus on JupyterLab while thinking about how our changes there will bubble up to RetroLab while at the same time being open to making changes to JupyterLab (and Lumino) that will allow RetroLab to customize the elements it inherits from JupyterLab so that they make sense and are more accessible within the context of the RetroLab UX

**Comment by trallard** [comment]
Marking as complete, but creating two following issues
